window.DRINKS = [
  {
    id: "wan-an-yang-cheng",
    category: "含酒精特调",
    name: "晚安羊城",
    alcoholType: "含酒精",
    metrics: { alcohol: 2, sweetness: 3, acidity: 3, body: 2, bubbles: 3 },
    flavors: ["柑橘", "花香", "气泡"],
    dairy: "无",
    caffeine: "无",
    spice: "无",
    avoidTags: ["herbal"],
    featuredRole: "fallback-alcohol",
    keywords: ["广州夜晚", "城市温柔", "归属"],
    productId: "16148724",
    miniProgramPath: "https://wxmpurl.cn/3kGWKSLpDma",
    price: 58,
    ingredients: "自制玫瑰花金酒、西柚糖浆、橙汁、接骨木花",
    story: [
      "听说一到午夜，广州就变成了巴黎。",
      "这座城市，白天太忙。只有到夜晚，才留下温柔。",
      "珠江上摇曳的灯光，骑楼里尘封的旧事，都随着酒馆中碰撞的杯声，一同睡去。",
    ],
    image: "./assets/drinks/wan-an-yang-cheng.jpeg",
  },
  {
    id: "lao-pai-yue-hui",
    category: "含酒精特调",
    name: "老派约会",
    alcoholType: "含酒精",
    metrics: { alcohol: 2, sweetness: 3, acidity: 3, body: 2, bubbles: 3 },
    flavors: ["酸甜", "莓果", "气泡"],
    dairy: "无",
    caffeine: "无",
    spice: "无",
    avoidTags: ["herbal"],
    keywords: ["老派爱情", "散步", "确定"],
    productId: "16148732",
    miniProgramPath: "https://wxmpurl.cn/VTZvVF4vi2q",
    price: 58,
    ingredients: "自制柠檬叶龙舌兰、蔓越莓、黑加仑、苏打水",
    story: [
      "时间太快，爱情太短。",
      "在这个纷扰的世界里，我依旧愿意和你散一次长长的步，久久地牵手。",
      "即使有点过时，但我也想笨拙地爱你。",
    ],
    image: "./assets/drinks/lao-pai-yue-hui.jpeg",
  },
  {
    id: "si-zai-gao-chao",
    category: "含酒精特调",
    name: "死在高潮",
    alcoholType: "含酒精",
    metrics: { alcohol: 2, sweetness: 3, acidity: 3, body: 2, bubbles: 3 },
    flavors: ["青苹果", "姜味", "辛香"],
    dairy: "无",
    caffeine: "无",
    spice: "有一点姜味/香料",
    avoidTags: ["spicy"],
    featuredRole: "signature",
    keywords: ["烟花", "盛大", "无遗憾"],
    productId: "16148728",
    miniProgramPath: "https://wxmpurl.cn/lApHIkGrQ7d",
    price: 68,
    ingredients: "自制柠檬叶金酒、青苹果、茉莉、藤椒、姜、苏打水",
    story: [
      "我们总渴望地久天长，但或许生如烟花，不妨在最灿烂的那刻落幕。",
      "不必善终，但留下盛大。不留余地，也不留遗憾。",
    ],
    image: "./assets/drinks/si-zai-gao-chao.jpeg",
  },
  {
    id: "wei-shuo-chu-kou-de-hua",
    category: "含酒精特调",
    name: "未说出口的话",
    alcoholType: "含酒精",
    metrics: { alcohol: 2, sweetness: 3, acidity: 3, body: 3, bubbles: 0 },
    flavors: ["烟熏", "伯爵茶", "木质调"],
    dairy: "无",
    caffeine: "有",
    spice: "无",
    avoidTags: ["caffeine", "tea", "herbal"],
    featuredRole: "signature",
    keywords: ["离别", "未尽之言", "后话"],
    productId: "16148722",
    miniProgramPath: "https://wxmpurl.cn/hzoBO6qcRem",
    price: 68,
    ingredients: "自制肉桂威士忌、苹果汁、伯爵茶、比特酒",
    story: [
      "那些真正想说的话，不在喧嚣琐碎里。",
      "你欲言又止，说：「那些都是后话了」。",
      "当一本书读完，一场电影散场，一杯酒喝完，一个人走远，那些没来得及说的话，应该有一个落脚的地方。",
    ],
    image: "./assets/drinks/wei-shuo-chu-kou-de-hua.jpeg",
  },
  {
    id: "bu-da-yang-cha-wu",
    category: "含酒精特调",
    name: "不打烊的沏茶屋",
    alcoholType: "含酒精",
    metrics: { alcohol: 2, sweetness: 4, acidity: 3, body: 2, bubbles: 3 },
    flavors: ["茶香", "清酒", "奶香"],
    dairy: "有",
    caffeine: "有",
    spice: "无",
    avoidTags: ["dairy", "caffeine", "tea"],
    keywords: ["深夜", "自由", "接纳"],
    productId: "16148736",
    miniProgramPath: "https://wxmpurl.cn/e7jUy9Lvm4j",
    price: 68,
    ingredients: "自制绿茶清酒、伏特加、日本蜜瓜酒、青苹果、绿茶、抹茶奶油",
    story: [
      "凌晨三点，城市终于学会了安静。",
      "那些白天不敢说的话，在茶杯里慢慢舒展开。",
      "不用赶时间，不用看眼色。这里没有打烊，也没有审判。一杯茶，和你本来的样子。",
    ],
    image: "./assets/drinks/bu-da-yang-cha-wu.jpeg",
  },
  {
    id: "da-sui-bo-li-bei",
    category: "含酒精特调",
    name: "打碎玻璃杯",
    alcoholType: "含酒精",
    metrics: { alcohol: 2, sweetness: 2, acidity: 4, body: 2, bubbles: 3 },
    flavors: ["香水", "柠檬", "气泡"],
    dairy: "无",
    caffeine: "无",
    spice: "无",
    avoidTags: [],
    keywords: ["释放", "叛逆", "打破完整"],
    productId: "16148743",
    miniProgramPath: "https://wxmpurl.cn/QXvGfzGvggo",
    price: 58,
    ingredients: "自制香水柠檬金酒、青苹果、蜜瓜、苏打水",
    story: [
      "有些杯子注定要碎。不是不小心，是故意的。",
      "太完整的日子，像一杯没气泡的苏打水。",
      "摔点什么吧。不一定是什么重要的东西。只是听个响，确认自己还活着。",
    ],
    image: "./assets/drinks/da-sui-bo-li-bei.jpeg",
  },
  {
    id: "yan-hua-xia-ri-ji",
    category: "含酒精特调",
    name: "烟花夏日祭",
    alcoholType: "含酒精",
    metrics: { alcohol: 2, sweetness: 3, acidity: 4, body: 1, bubbles: 0 },
    flavors: ["奶香", "热带", "酸甜"],
    dairy: "有",
    caffeine: "无",
    spice: "无",
    avoidTags: ["dairy"],
    keywords: ["夏日", "烟花", "共同愿望"],
    productId: "16139502",
    miniProgramPath: "https://wxmpurl.cn/hoFpJ1gpCIi",
    price: 58,
    ingredients: "自制乳清奶洗金朗姆、菠萝、芒果、百香果、柠檬酸、乳清奶洗、自制香草奶油",
    story: [
      "花火升空的那几秒，所有人都仰着头。没人说话，没人看手机。",
      "我们短暂地，共享了同一个愿望。",
      "夏天会结束，烟花会熄灭。但那一瞬的灿烂，够记一辈子。",
    ],
    image: "./assets/drinks/yan-hua-xia-ri-ji.jpeg",
  },
  {
    id: "se-gu-ye-jie",
    category: "无酒精",
    name: "涩谷夜街",
    alcoholType: "无酒精",
    metrics: { alcohol: 0, sweetness: 3, acidity: 3, body: 0, bubbles: 3 },
    flavors: ["酸甜", "植物", "气泡"],
    dairy: "无",
    caffeine: "有",
    spice: "无",
    avoidTags: ["caffeine"],
    keywords: ["都市独行", "自由", "自我"],
    productId: "16139503",
    miniProgramPath: "https://wxmpurl.cn/6pfkaSYdn7h",
    price: 48,
    ingredients: "粉色魔爪、薰衣草、洛神花、黑加仑、莓果、芭乐、苏打水",
    story: [
      "一个人穿过涩谷的十字路口。周围全是人，但没有一个人认识你。",
      "这种自由，比酒精更让人上瘾。",
      "霓虹灯把你的影子拉得很长。你终于可以，只是你自己。",
    ],
    image: "./assets/drinks/se-gu-ye-jie.jpeg",
  },
  {
    id: "cong-yuan-ye-gui-lai",
    category: "无酒精",
    name: "从原野归来",
    alcoholType: "无酒精",
    metrics: { alcohol: 0, sweetness: 4, acidity: 3, body: 0, bubbles: 3 },
    flavors: ["植物", "咸香", "气泡"],
    dairy: "无",
    caffeine: "有",
    spice: "无",
    avoidTags: ["caffeine", "tea"],
    keywords: ["远行", "归来", "少年"],
    productId: "16139505",
    miniProgramPath: "https://wxmpurl.cn/eM0QE1mmhUh",
    price: 48,
    ingredients: "话梅、海盐焦糖、紫苏、西柚、红茶、苏打水",
    story: [
      "走过山川，行过河海。历经坎坷，也到顶峰。",
      "我们寻寻觅觅，但发现世界是一个圆。那些珍贵的人和事，其实一直在你身边。",
      "人生是原野，祝你归来仍是少年。",
    ],
    image: "./assets/drinks/cong-yuan-ye-gui-lai.jpeg",
  },
  {
    id: "yi-zhi-tang-dao-sheng-huo-bian-hao",
    category: "无酒精",
    name: "一直躺到生活变好",
    alcoholType: "无酒精",
    metrics: { alcohol: 0, sweetness: 4, acidity: 0, body: 0, bubbles: 0 },
    flavors: ["红豆", "茶香", "奶香"],
    dairy: "有",
    caffeine: "有",
    spice: "无",
    avoidTags: ["dairy", "caffeine", "tea"],
    keywords: ["放松", "躺平", "慢下来"],
    productId: "16139512",
    miniProgramPath: "https://wxmpurl.cn/9slBXqLeluq",
    price: 58,
    ingredients: "红豆、抹茶、咖啡、奶油、牛奶",
    story: [
      "放轻松，就不会沉下去。",
      "别急着垂直，走好你的弯路。慢一点，也没关系。",
      "让自己快乐，才叫做意义。",
    ],
    image: "./assets/drinks/yi-zhi-tang-dao-sheng-huo-bian-hao.png",
  },
  {
    id: "yu-ren",
    category: "无酒精",
    name: "愚人",
    alcoholType: "无酒精",
    metrics: { alcohol: 0, sweetness: 2, acidity: 3, body: 0, bubbles: 0 },
    flavors: ["香料", "茶香", "咖啡"],
    dairy: "无",
    caffeine: "有",
    spice: "无",
    avoidTags: ["caffeine", "tea"],
    featuredRole: "signature-zero",
    keywords: ["出发", "冒险", "可能性"],
    productId: "16139510",
    miniProgramPath: "https://wxmpurl.cn/MkOmKibhmci",
    price: 58,
    ingredients: "苹果、肉桂、伯爵茶、咖啡",
    story: [
      "塔罗牌里第一张就是愚人。",
      "他站在悬崖边，不看脚下，只管向前走。别人笑他傻。",
      "但他知道，所有伟大的故事，都始于一次不管不顾的出发。笨一点，反而走得远。",
    ],
    image: "./assets/drinks/yu-ren.png",
  },
  {
    id: "herstory",
    category: "无酒精",
    name: "她说herstory",
    alcoholType: "无酒精",
    metrics: { alcohol: 0, sweetness: 3, acidity: 2, body: 0, bubbles: 0 },
    flavors: ["花茶", "果香", "橘子香"],
    dairy: "无",
    caffeine: "无",
    spice: "无",
    avoidTags: ["tea"],
    featuredRole: "fallback-zero",
    keywords: ["自我叙事", "女性", "表达"],
    productId: "16139495",
    miniProgramPath: "https://wxmpurl.cn/vN1n9nc71mr",
    price: 48,
    ingredients: "洛神花茶、橙子、苹果、黑加仑",
    story: ["我们都拥有自己的叙事！"],
    image: "./assets/drinks/herstory.jpeg",
  },
  {
    id: "gin-tonic",
    category: "经典鸡尾酒",
    name: "金汤力",
    alcoholType: "含酒精",
    metrics: { alcohol: 3, sweetness: 2, acidity: 3, body: 2, bubbles: 3 },
    flavors: ["杜松子", "柑橘", "奎宁苦味"],
    dairy: "无",
    caffeine: "无",
    spice: "无",
    avoidTags: [],
    keywords: ["松弛", "夜晚"],
    productId: "15734880",
    miniProgramPath: "https://wxmpurl.cn/FWS5Lm4n4Ti",
    price: 58,
    ingredients: "自制拼配金酒、汤力水、青柠",
    story: [],
    image: "./assets/drinks/gin-tonic.jpeg",
  },
  {
    id: "highball",
    category: "经典鸡尾酒",
    name: "highball",
    alcoholType: "含酒精",
    metrics: { alcohol: 3, sweetness: 1, acidity: 1, body: 2, bubbles: 3 },
    flavors: ["威士忌", "木质/谷物", "苏打清爽感"],
    dairy: "无",
    caffeine: "无",
    spice: "无",
    avoidTags: [],
    keywords: ["松弛", "独处", "下班"],
    productId: "15734879",
    miniProgramPath: "https://wxmpurl.cn/mn60dIM3bXh",
    price: 58,
    ingredients: "威士忌、苏打水、柠檬皮",
    story: [],
    image: "./assets/drinks/highball.jpeg",
  },
  {
    id: "cuba-libre",
    category: "经典鸡尾酒",
    name: "自由古巴",
    alcoholType: "含酒精",
    metrics: { alcohol: 3, sweetness: 4, acidity: 3, body: 3, bubbles: 3 },
    flavors: ["可乐", "朗姆酒", "青柠"],
    dairy: "无",
    caffeine: "无",
    spice: "无",
    avoidTags: [],
    keywords: ["自由", "出走", "盛夏"],
    productId: "15734881",
    miniProgramPath: "https://wxmpurl.cn/IlakRj4gx1a",
    price: 58,
    ingredients: "黑朗姆、可乐、青柠",
    story: [],
    image: "./assets/drinks/cuba-libre.jpeg",
  },
];
